Feature/di movies linking tutorial ecc 4637
eccenca/documentation.eccenca.com pull request #112
Opened 2023-03-06 14:50 UTC by rpietzsch

closes https://jira.brox.de/browse/ECC-4637

2023-03-24 15:34 UTC, seebi commented
Most of the images have cropping issues. Please look into them. Some have artifacts, some are not on 23.1 but 22.2.

2023-03-24 15:34 UTC, seebi requested changes
Please see all my comments ...

2023-03-24 15:34 UTC, seebi commented on docs/build/create-project-with-linkingrule/index.md
> +-   Click on **add file** on the right side of the page.
Its `Add File` on the screenshot.

2023-03-24 15:34 UTC, seebi commented on docs/build/create-project-with-linkingrule/index.md
> +-   Click on **drop files here** select the file and click on **open**.
Its `Drop files here or browse` on the screenshot.

2023-03-24 15:34 UTC, seebi commented on docs/build/create-project-with-linkingrule/index.md
> +-   Click on **drop files here** select the file and click on **open**.
also `Open`

2023-03-24 15:34 UTC, seebi commented on docs/build/create-project-with-linkingrule/index.md
> +-   Click on **create.**
- icon missing
- capitalisation wrong

(I will not mark missing icons or wrong capitalisation in the rest of the review)

2023-03-24 15:34 UTC, seebi commented on docs/build/create-project-with-linkingrule/index.md
> +-   Click on the **dataset** on the left side in the item type and double-click on the **CSV file** in the centre.
a double click? I am not aware of this - please validate.

2023-03-24 15:34 UTC, seebi commented on docs/build/create-project-with-linkingrule/index.md
> +    ![image](22.2-files-added.png){ width="75%"}
The files have two `.csv` suffixes. This is not exactly wrong but awkward. I would change it.

2023-03-24 15:34 UTC, seebi commented on docs/build/create-project-with-linkingrule/index.md
> +-   Click on the **dataset** on the left side in the item type and double-click on the **CSV file** in the centre.
ok, a double click is indeed possible.
But the default workflow is singe click + click on "Add" so I suggest to describe the default workflow.

2023-03-24 15:34 UTC, seebi commented on docs/build/create-project-with-linkingrule/index.md
> +    ![image](22.2-click-on-create1.png){ width="75%"}
The image is cropped wrongly so it looks ugly.

2023-03-24 15:34 UTC, seebi commented on docs/build/create-project-with-linkingrule/index.md
> +    ![image](22.2-click-on-create1.png){ width="75%"}
I mean that the buttons are not completely seen and that there is a black line on the right.

2023-03-24 15:34 UTC, seebi commented on docs/build/create-project-with-linkingrule/index.md
> +    ![image](22.2-linking-created.png){ width="75%"}
badly cropped

2023-03-24 15:34 UTC, seebi commented on docs/build/create-project-with-linkingrule/index.md
> +    ![image](22.2-linking-created.png){ width="75%"}
badly cropped

2023-03-24 15:34 UTC, seebi commented on docs/build/create-project-with-linkingrule/index.md
> +    ![image](22.2-linking-created.png){ width="75%"}
badly cropped

2023-03-24 15:34 UTC, seebi commented on docs/build/create-project-with-linkingrule/index.md
> +-   Click on **comparison** and type the **equality** in the search field and drag the `string equality` operation onto the canvas.
`**comparison**` -> `**Comparison (:eccenca-operation-comparison:)**`

2023-03-24 15:34 UTC, seebi commented on docs/build/create-project-with-linkingrule/index.md
> +    ![image](22.2-expand-result.png){ width="75%"}
This screen has changed in 23.1 - please update.

2023-03-24 15:34 UTC, seebi commented on docs/build/create-project-with-linkingrule/linkexecution.png
remove lower windows bar and white screen.

2023-03-24 15:34 UTC, seebi commented on docs/build/create-project-with-linkingrule/linking-evaluation.png
editor menu is somehow under the main bar

2023-03-24 15:34 UTC, seebi commented on docs/build/create-project-with-linkingrule/linking-result.png
There is an error sign ( top right (!) ) which indicates an error here. we should not have this on the screen

2023-03-24 15:34 UTC, seebi commented on docs/build/create-project-with-linkingrule/linking-save.png
black line on the right could be removed

2023-03-24 15:34 UTC, seebi commented on docs/build/create-project-with-linkingrule/linking-save.png
also badly cropped

2023-03-24 15:34 UTC, seebi commented on docs/build/create-project-with-linkingrule/linking.png
This is nicely cropped ... :)

2023-03-24 15:34 UTC, seebi commented on docs/build/create-project-with-linkingrule/lower-equality.png
badly cropped on top

2023-03-24 15:34 UTC, seebi commented on docs/build/create-project-with-linkingrule/save.png
left menu cutted

2023-03-24 15:34 UTC, seebi commented on docs/build/create-project-with-linkingrule/shaft.png
What about the blue artifacts?

2023-03-24 15:34 UTC, seebi commented on docs/build/create-project-with-linkingrule/source-path.png
what is black artifact on the lower right?

2023-03-24 15:34 UTC, seebi commented on docs/build/create-project-with-linkingrule/source-target-path.png
what is black artifact on the lower right?

2023-03-24 15:34 UTC, seebi commented on docs/build/create-project-with-linkingrule/transformation .png
left menu cutted

2023-03-24 15:34 UTC, seebi commented on docs/build/create-project-with-linkingrule/transformation1.png
left menu cutted

2023-03-24 19:55 UTC, rpietzsch commented on docs/build/create-project-with-linkingrule/shaft.png
img not in use, pruned.

2023-03-24 19:55 UTC, rpietzsch commented on docs/build/create-project-with-linkingrule/source-target-path.png
img not in use, pruned

2023-03-24 19:55 UTC, rpietzsch commented on docs/build/create-project-with-linkingrule/transformation1.png
img not in use, pruned

2023-03-24 19:56 UTC, rpietzsch commented on docs/build/create-project-with-linkingrule/source-path.png
img not in use, pruned

2023-03-29 07:24 UTC, rpietzsch commented on docs/build/create-project-with-linkingrule/index.md
> +-   Once logged in to Corporate memory on the right side click on **create.**
extended.

2024-02-19 15:42 UTC, seebi commented
@rpietzsch How to proceed on this?

2024-07-29 09:06 UTC, closed without merging