Feature/snowflake tutorial ecc 4683
eccenca/documentation.eccenca.com pull request #130
Opened 2023-05-26 09:11 UTC by rpietzsch

2023-05-26 09:49 UTC, seebi requested changes
Please remove all old files
Please rename files accordingly

I can do a second review afterwards.

2023-05-26 09:49 UTC, seebi commented on docs/build/snowflake-tutorial/22.2-Product-name-database.png
All snowflake screenshots should be prefixed with `snowlflake-` not `22.2.`.

All files should be lower cased only, (not `Product`).

2023-05-26 09:49 UTC, seebi commented on docs/build/snowflake-tutorial/22.2-add-databasenew.png
Why do we have 2 screens of the same content? Please remove one.

2023-05-26 09:49 UTC, seebi commented on docs/build/snowflake-tutorial/22.2-add-projectnew.png
same file again?

2023-05-26 09:49 UTC, seebi commented on docs/build/snowflake-tutorial/22.2-add-schema.png
cropping not correct

2023-05-26 09:49 UTC, seebi commented on docs/build/snowflake-tutorial/22.2-add-value.png
cropping not correct

2023-05-26 09:49 UTC, seebi commented on docs/build/snowflake-tutorial/22.2-advanced.png
cropping not correct

naming to generic

2023-05-26 09:49 UTC, seebi commented on docs/build/snowflake-tutorial/22.2-create-project.png
cropping not correct

2023-05-26 09:49 UTC, seebi commented on docs/build/snowflake-tutorial/22.2-custome-pattern.png
cropping not correct

2023-05-26 09:49 UTC, seebi commented on docs/build/snowflake-tutorial/22.2-databas-name.png
cropping not correct

2023-05-26 09:49 UTC, seebi commented on docs/build/snowflake-tutorial/22.2-database-created.png
cropping not correct

2023-05-26 09:49 UTC, seebi commented on docs/build/snowflake-tutorial/22.2-easynav-graph.png
cropping not correct

2023-05-26 09:49 UTC, seebi commented on docs/build/snowflake-tutorial/22.2-graph-target.png
cropping not correct

2023-05-26 09:49 UTC, seebi commented on docs/build/snowflake-tutorial/22.2-graph-uri.png
cropping not correct

2023-05-26 09:49 UTC, seebi commented on docs/build/snowflake-tutorial/22.2-graph-urinew.png
cropping not correct

2023-05-26 09:49 UTC, seebi commented on docs/build/snowflake-tutorial/22.2-graph.png
cropping not correct

2023-05-26 09:49 UTC, seebi commented on docs/build/snowflake-tutorial/22.2-jdbc-created.-new.png
cropping not correct

file name wrong

remove all "new" from names

2023-05-26 09:49 UTC, seebi commented on docs/build/snowflake-tutorial/22.2-jdbc-created.-newpng
file name wrong

2023-05-26 09:49 UTC, seebi commented on docs/build/snowflake-tutorial/22.2-jdbc-created.png
cropping not correct

2023-05-26 09:49 UTC, seebi commented on docs/build/snowflake-tutorial/22.2-mapping-rule.png
cropping not correct

2023-05-26 09:49 UTC, seebi commented on docs/build/snowflake-tutorial/22.2-mapping-rulenew.png
remove all `new` from names

2023-05-26 09:49 UTC, seebi commented on docs/build/snowflake-tutorial/22.2-organization-number.png
cropping not correct

2023-05-26 09:49 UTC, seebi commented on docs/build/snowflake-tutorial/22.2-output.png
cropping not correct

2023-05-26 09:49 UTC, seebi commented on docs/build/snowflake-tutorial/22.2-project-name.png
cropping not correct

2023-05-26 09:49 UTC, seebi commented on docs/build/snowflake-tutorial/22.2-suggestion-result.png
cropping not correct

2023-05-26 09:49 UTC, seebi commented on docs/build/snowflake-tutorial/22.2-suggestion-resultnew.png
remove all `new` from names

2023-05-26 09:49 UTC, seebi commented on docs/build/snowflake-tutorial/22.2-suggestions.png
cropping not correct

2023-05-26 09:49 UTC, seebi commented on docs/build/snowflake-tutorial/22.2-suggestionsnew.png
remove all `new` from names

2023-05-26 09:49 UTC, seebi commented on docs/build/snowflake-tutorial/22.2-target-entity-newpng.png
remove all `new` from names

2023-05-26 09:49 UTC, seebi commented on docs/build/snowflake-tutorial/22.2-target-product.png
cropping not correct

2023-05-26 09:49 UTC, seebi commented on docs/build/snowflake-tutorial/22.2-target-property.png
cropping not correct

2023-05-26 09:49 UTC, seebi commented on docs/build/snowflake-tutorial/22.2-target-propertynew.png
remove all `new` from names

2023-05-26 09:49 UTC, seebi commented on docs/build/snowflake-tutorial/22.2-tick.png
cropping not correct

2023-05-26 09:49 UTC, seebi commented on docs/build/snowflake-tutorial/22.2-ticknew.png
remove all `new` from names

2023-05-30 06:27 UTC, rpietzsch commented
@seebi please recheck.

- deleted duplicate / obsolete images
- images using style class (`bordered`) instead of of inline markup
- changed image filename prefix to `snowflake-`
- refined cropping of some images (removed borders, scrollbars, etc.)

2023-06-07 17:38 UTC, seebi approved these changes

2023-06-07 17:47 UTC, seebi approved these changes

2023-06-07 17:57 UTC, closed without merging